name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image for Backend
      run: docker build -t anaseg/banking-application:backend-latest .

    - name: Push Docker Image to Docker Hub
      run: docker push anaseg/banking-application:backend-latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image from Docker Hub
        run: docker pull anaseg/banking-application:backend-latest

      - name: Stop and Remove Existing Backend Container
        run: |
          # Stop the container if it is running
          docker stop banking-application-backend-latest || echo "No running container found"
          # Remove the container (even if stopped) to ensure a clean start
          docker rm banking-application-backend-latest || echo "No container to remove"

      - name: Run Backend Docker Container
        run: |
          docker run -d -p 4000:4000 --name banking-application-backend-latest \
          -e MONGO_URI="${{ secrets.MONGO_URI }}" \
          -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
          -e PORT=4000 \
          anaseg/banking-application:backend-latest




